language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_byob;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: S5LNB688RYz+7e9mHe48/zX7URbaNzFjLz5qzT1n1OoyREMyjFim3sVH5n2XFG1/6gedgkOwRzjtLYU0zHJ0wRj47k5qmt0GpJ2YXHUGMwQdyw+Ge57v8n+fY8RdPLvDDCiddCB/TWhC3Gc2o2d7CNhk6ENAXG5s7b41OU+gPEeXsY4AciRbb0G1hYyaEtTqa9O3PgCXaVvY+tWeg9WExFnsjkpiia5lEmeg3/y8h73AIN/L2vOXrjWnGmQ6YxT3l2lI/3K5X9BVlSb9hts7cUI4UhgCtOegaMsyde2DfU1y6cF4mcdP8ZEtUDi9ZMASIu7+Cy26KD2Fj8XXyPO6m13wuhrJpSfJJEbi43KO6ZTIpHUKW5PRDAXcs4CYbooRHPk+jTTzJ8weZcpQeW+JKfSMMYOS4yBc2oNAy5F3Bnjh2kRNEyG5xJRN8oGSjjy3HYOxLTtCp3BACba4w5a5hHRkQwuUKQi16JkaCPWnF0fE81FJBdw/CeQGf68expdFpse5gDTS9PXl5h2yxMNQKOR2JK5KX+iiQPyZfBfWJZNg2MwBg+d50eGwETWQ7gWIQGOhVON5fRmG8Sb5pqGVXMkCGSsJ7Dq8kIARTKP/u4L11YrXhTRO69qT2ff8XFPaBemdM0cDO39huBZQ7WYWXSdYVhw1/p80A90YZm/Fnz4=
    app: byobrew
    skip_cleanup: true